In [2]:
import numpy as np
import pandas as pd

In [3]:
nba_pct=pd.read_csv('nba_team_adv_for_comparison.csv')
euro_pct=pd.read_csv('euroleague_advanced.csv')
nba_ratings=pd.read_csv('nba_teams_adv.csv')
euro_ratings=pd.read_csv('euroleague_ratings.csv')

In [4]:
nba_pct_mean=pd.pivot_table(nba_pct,values=['Ast%','ST%','BLK%'], index=['Year'],aggfunc='mean')
euro_pct_mean=pd.pivot_table(euro_pct,values=['Ast%','ST%','BLK%'], index=['Year'],aggfunc='mean')

In [5]:
nba_ratings_mean=pd.pivot_table(nba_ratings,values=['ORtg/A','DRtg/A'],index=['year'],aggfunc='mean')
euro_ratings_mean=pd.pivot_table(euro_ratings,values=['Off Rat','Def Rat'],index=['Year'],aggfunc='mean')

In [6]:
nba=nba_pct_mean.join(nba_ratings_mean)
euro=euro_pct_mean.join(euro_ratings_mean)

In [7]:
diffs=pd.DataFrame(index=nba.index)

In [8]:
diffs['Ast%']=nba['Ast%']-euro['Ast%']
diffs['BLK%']=nba['BLK%']-euro['BLK%']
diffs['ST%']=nba['ST%']-euro['ST%']
diffs['Off Rat']=nba['ORtg/A']-euro['Off Rat']
diffs['Def Rat']=nba['DRtg/A']-euro['Def Rat']

In [9]:
diffs

                Ast%      BLK%       ST%   Off Rat   Def Rat
Year
2000-2001  22.960908  2.473380 -5.772284 -3.040054 -5.138825
2001-2002  17.906913  2.077220 -3.461206 -2.402734 -3.878508
2002-2003  16.277755  1.599054 -3.667583 -5.199431 -6.351195
2003-2004  14.146576  2.026083 -4.370131 -6.901844 -8.124476
2004-2005  12.169606  1.103552 -5.701142 -0.912547 -2.190587
2005-2006   9.928180  1.123305 -7.316819  2.022229  0.623015
2006-2007  10.549490  0.954841 -7.588072  1.027470 -0.192196
2007-2008  11.634220  0.669697 -4.777862  0.972556 -0.347978
2008-2009  10.848063  0.819937 -3.530776  2.216762 -0.125203
2009-2010   4.801514  0.575608 -2.712300  2.779933  0.951840
2010-2011   6.867925  1.205299 -1.766074  4.137008  2.214854
2011-2012   5.891960  1.452636 -0.349222  1.176437 -1.106618
2012-2013   6.424820  1.632488  0.220930  0.913075 -1.252144
2013-2014   1.005938  1.022082 -0.685226  0.472059 -2.014210
2014-2015  -1.518673  1.047136 -0.921246 -1.363498 -3.461094
2015-2016  -4.213965  1.238151 -0.870939  0.468933 -2.139540
2016-2017  -3.180294  1.285370 -1.223896 -0.756115 -1.096675
2017-2018  -2.474964  1.831045 -0.883225 -4.816846 -5.228074
2018-2019  -0.017166  2.235162 -1.432756 -2.275492 -2.784053
2019-2020  -0.607500  2.265732 -1.571930 -1.157569 -0.994236
2020-2021  -1.597238  2.451260 -1.997452  0.908083  0.536681
2021-2022   1.854651  2.833257 -1.613016  2.195333  1.942092